version: "3.1"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8070:8080
volumes:
  database:
