version: "3.1"
services:
  # app:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - "5050:5050"
  #   command: yarn dev
  #   volumes:
  #     - .:/app/
  #     - /app/node_modules
  db:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8070:8080
volumes:
  database:
